only GmfLut & NcLutModel
umr-lops/grdwindinversion pull request #82
Opened 2024-10-01 03:52 UTC by vincelhx

my change concern the xsarsea PR also that delete sarwing luts

2024-10-01 03:52 UTC, vincelhx commented
I think we need to merge #81 from @Skealz at the same time

2024-10-01 12:12 UTC, agrouaze requested changes
`travis` to remove.

2024-10-01 12:12 UTC, agrouaze commented on grdwindinversion/.travis.yml
`travis` is supposed to help for CI tests, I think we don't use it in `grdwindinversion`, 
Also, I suspect that `agrouaze/grdwindinversion` is the initial repo URL... 
I suggest to remove it, unless you plan to use it in the future.

2024-10-01 12:50 UTC, Skealz commented
> I think we need to merge #81 from @Skealz at the same time

Don't wait for the merge of my PR

2024-10-04 13:56 UTC, vincelhx commented on grdwindinversion/.travis.yml
done

2024-10-10 08:06 UTC, agrouaze approved these changes

2024-10-10 11:31 UTC, merged